# Generated by Django 4.1.2 on 2022-10-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConctactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="Correo")),
                ("subject", models.CharField(max_length=255, verbose_name="Asunto")),
                ("content", models.TextField(verbose_name="Descripccion")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["created"],
            },
        ),
    ]
