# Generated by Django 4.1.2 on 2022-10-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["created"],
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
            },
        ),
    ]
