# Generated by Django 4.1.2 on 2022-10-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["created"],
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
            },
        ),
    ]
