# Generated by Django 4.1.2 on 2022-10-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_category_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-<function uuid4 at 0x000002CF9A5CEB80>",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
