# Generated by Django 4.1.2 on 2022-10-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-<function uuid4 at 0x000001FFC496EB80>",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
