# Generated by Django 4.1.2 on 2022-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="0a5185da-865c-4005-9790-477fcba5a56d", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-0a5185da-865c-4005-9790-477fcba5a56d",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
