# Generated by Django 4.1.2 on 2022-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="64c2b2f7-b3b8-4ed2-80b8-dcfedf596613", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-64c2b2f7-b3b8-4ed2-80b8-dcfedf596613",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
