# Generated by Django 4.1.2 on 2022-10-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="6ae350e8-8cf8-4e1f-a60e-64baa858c10b", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-6ae350e8-8cf8-4e1f-a60e-64baa858c10b",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
