# Generated by Django 4.1.2 on 2022-10-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="69065f90-3c67-444d-85c7-5765d241b0ad", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-69065f90-3c67-444d-85c7-5765d241b0ad",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
