# Generated by Django 4.1.2 on 2022-10-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="5ee44235-3178-4748-a6e0-441a69313e47", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-5ee44235-3178-4748-a6e0-441a69313e47",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
