# Generated by Django 4.1.2 on 2022-10-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_post_blog_uuid_alter_post_slug_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="emial", new_name="email",
        ),
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="488e7d58-3a13-4049-b052-ce698eaa1dee", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-488e7d58-3a13-4049-b052-ce698eaa1dee",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
