# Generated by Django 4.1.2 on 2022-10-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_alter_post_author_alter_post_blog_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="1582ddf6-239a-4c44-a156-fe273eac84b4", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-1582ddf6-239a-4c44-a156-fe273eac84b4",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
