# Generated by Django 4.1.2 on 2022-10-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="637abb7c-ec94-43fe-9a1e-bebc62f29208", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-637abb7c-ec94-43fe-9a1e-bebc62f29208",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
