# Generated by Django 4.1.2 on 2022-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="f45f5ce8-3edc-425e-bde7-57739816a1a2", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-f45f5ce8-3edc-425e-bde7-57739816a1a2",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
