# Generated by Django 4.1.2 on 2022-10-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="7e7de11f-b1cd-4a1a-a50f-799dd0bbbff7", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-7e7de11f-b1cd-4a1a-a50f-799dd0bbbff7",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
