# Generated by Django 4.1.2 on 2022-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="e2815c46-ac5d-4e5d-b423-c518f7c2400e", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-e2815c46-ac5d-4e5d-b423-c518f7c2400e",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
