# Generated by Django 4.1.2 on 2022-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="31dae1f0-81e6-4823-91cd-d16e1733c555", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-31dae1f0-81e6-4823-91cd-d16e1733c555",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
