# Generated by Django 4.1.2 on 2022-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0033_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="8609e18d-6ecf-428e-8171-ddf7d682f1f4", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-8609e18d-6ecf-428e-8171-ddf7d682f1f4",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
