# Generated by Django 4.1.2 on 2022-10-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0034_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="a3153804-e989-44ce-abf6-12c1e040faba", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-a3153804-e989-44ce-abf6-12c1e040faba",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
