# Generated by Django 4.1.2 on 2022-10-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0035_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="c551a46a-9a2f-4dce-8054-d0e5a788e9e6", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-c551a46a-9a2f-4dce-8054-d0e5a788e9e6",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
