# Generated by Django 4.1.2 on 2022-10-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0036_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="434e531b-a116-4ff8-bb05-1ac1e82c4b79", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-434e531b-a116-4ff8-bb05-1ac1e82c4b79",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
