# Generated by Django 4.1.2 on 2022-10-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0037_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="d4940cf6-ee1a-4630-96ae-b34493ca546e", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-d4940cf6-ee1a-4630-96ae-b34493ca546e",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
