# Generated by Django 4.1.2 on 2022-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0038_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="31a4cd5f-9334-48dc-93a7-b61eb40c2d6e", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-31a4cd5f-9334-48dc-93a7-b61eb40c2d6e",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
