# Generated by Django 4.1.2 on 2022-10-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0039_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="2a0c6464-67eb-44e3-aed6-0ed3adf41b4d", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-2a0c6464-67eb-44e3-aed6-0ed3adf41b4d",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
