# Generated by Django 4.1.2 on 2022-10-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0041_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="c3b02aaa-7c77-4bd3-95b2-536164b7ca34", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-c3b02aaa-7c77-4bd3-95b2-536164b7ca34",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
