# Generated by Django 4.1.2 on 2022-10-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0042_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="9b07911b-47d8-4530-87d1-e1352201a3fe", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-9b07911b-47d8-4530-87d1-e1352201a3fe",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
