# Generated by Django 4.1.2 on 2022-10-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0043_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="4575e6ae-e3e2-458a-b144-7838bb7ce884", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-4575e6ae-e3e2-458a-b144-7838bb7ce884",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
