# Generated by Django 4.1.2 on 2022-10-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0044_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="9e7658e5-1247-4eae-8deb-f1a8c98c2aa2", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-9e7658e5-1247-4eae-8deb-f1a8c98c2aa2",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
