# Generated by Django 4.1.2 on 2022-10-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0045_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="f6691f47-3165-41b7-bbde-952c9671e8e4", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-f6691f47-3165-41b7-bbde-952c9671e8e4",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
