# Generated by Django 4.1.2 on 2022-10-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0046_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="17408cac-d1f4-4c31-a0d0-ad06d5738515", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-17408cac-d1f4-4c31-a0d0-ad06d5738515",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
