# Generated by Django 4.1.2 on 2022-10-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0048_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="9bbde057-76ab-410d-a9e2-e0ff5f9896f5", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-9bbde057-76ab-410d-a9e2-e0ff5f9896f5",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
