# Generated by Django 4.1.2 on 2022-10-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0049_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="61ac0616-4cee-429b-b82c-2a368571a8ae", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-61ac0616-4cee-429b-b82c-2a368571a8ae",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
