# Generated by Django 4.1.2 on 2022-10-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0052_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="6ee1a77e-8bc1-4e04-ac18-24c35b57e009", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-6ee1a77e-8bc1-4e04-ac18-24c35b57e009",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
