# Generated by Django 4.1.2 on 2022-10-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0053_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="fb8b2f37-5c11-4fcd-9799-5d6fb4f1ca72", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-fb8b2f37-5c11-4fcd-9799-5d6fb4f1ca72",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
