# Generated by Django 4.1.2 on 2022-10-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0054_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="1dcfcd01-bd18-4b70-8be4-ffdbec108891", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-1dcfcd01-bd18-4b70-8be4-ffdbec108891",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
