# Generated by Django 4.1.2 on 2022-10-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0055_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="65d467b3-01de-4d3c-8e55-17e5543e34e4", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-65d467b3-01de-4d3c-8e55-17e5543e34e4",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
