# Generated by Django 4.1.2 on 2022-10-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0056_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="a12008af-6209-4fa4-9eea-bef6197aec64", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-a12008af-6209-4fa4-9eea-bef6197aec64",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
