# Generated by Django 4.1.2 on 2022-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0057_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="84f1f8b4-718e-4ca2-847f-a3f3aacc410b", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-84f1f8b4-718e-4ca2-847f-a3f3aacc410b",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
