# Generated by Django 4.1.2 on 2022-10-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0059_alter_post_blog_uuid_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_uuid",
            field=models.UUIDField(
                default="5c1dcead-29e2-4a88-8224-af0615f1944c", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="blog-5c1dcead-29e2-4a88-8224-af0615f1944c",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
