# Generated by Django 4.1.5 on 2023-01-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_alter_post_blog_uuid_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_uuid',
            field=models.UUIDField(default='a47c069e-707d-45c2-857e-59a47929a7f6', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='blog-a47c069e-707d-45c2-857e-59a47929a7f6', unique=True, verbose_name='URL (sin espacios)'),
        ),
    ]
