# Generated by Django 4.1.7 on 2023-02-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_alter_post_blog_uuid_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_uuid',
            field=models.UUIDField(default='e50be374-c634-48a4-a5ff-f8811f4f04e8', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='blog-e50be374-c634-48a4-a5ff-f8811f4f04e8', unique=True, verbose_name='URL (sin espacios)'),
        ),
    ]
