# Generated by Django 4.1.2 on 2022-10-18 03:52

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_auto_20210418_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="no-avatar.jpg", upload_to=registration.models.custom_upload_to
            ),
        ),
    ]
