# Generated by Django 4.1.2 on 2022-10-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlmodel",
            name="css_skills_percentage",
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="db_skills_percentage",
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="html_skills_percentage",
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="js_skills_percentage",
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="py_skills_percentage",
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
    ]
