# Generated by Django 4.1.2 on 2022-10-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_htmlmodel_css_skills_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlmodel",
            name="css_skills_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="db_skills_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="html_skills_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="js_skills_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="htmlmodel",
            name="py_skills_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
