# Generated by Django 4.1.5 on 2023-01-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_htmlmodel_css_skills_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('score', models.CharField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Regular'), (4, 'Good'), (5, 'Exelent')], default=5, max_length=1)),
                ('comments', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
    ]
