# Generated by Django 4.1.7 on 2023-02-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_testimonials_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='comments',
            field=models.TextField(max_length=500),
        ),
    ]
