# Generated by Django 4.1.2 on 2022-10-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_delete_projectmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-<function uuid4 at 0x0000023934C7EB80>",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
