# Generated by Django 4.1.2 on 2022-10-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-<function uuid4 at 0x000001AA386EEB80>",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
