# Generated by Django 4.1.2 on 2022-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_date",
            field=models.DateTimeField(verbose_name="Fecha de elaboracion"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-<function uuid4 at 0x00000234D3E2EB80>",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
