# Generated by Django 4.1.2 on 2022-10-16 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="categories",
            field=models.ManyToManyField(
                to="portfolio.category", verbose_name="Categoria"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de elaboracion"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-b5f783ee-99c9-4921-88a3-56bdc75f00f5",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
