# Generated by Django 4.1.2 on 2022-10-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0007_alter_project_categories_alter_project_project_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-9d4735ca-8155-4ab8-ad54-f5746a5e9403",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
