# Generated by Django 4.1.2 on 2022-10-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="images",
            field=models.FileField(
                blank=True, null=True, upload_to="portfolio", verbose_name="Imagenes"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-6f57a0c8-09bb-4d5a-8732-6c3a1207d3db",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
