# Generated by Django 4.1.2 on 2022-10-16 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0009_alter_project_images_alter_project_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="contributors",),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-c2ccdcfb-ebbd-4be0-8152-fa7fe10f056a",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Colaboradores"
            ),
        ),
    ]
