# Generated by Django 4.1.2 on 2022-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_remove_project_contributors_alter_project_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-b7e7b949-3530-4390-837b-4e93759b3fcb",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
