# Generated by Django 4.1.2 on 2022-10-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-a522777c-b3d3-48d4-9f18-9b05bb38717f",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
