# Generated by Django 4.1.2 on 2022-10-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-09661b16-8316-4843-a8b2-623c513f4dd5",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
