# Generated by Django 4.1.2 on 2022-10-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-7d174827-0ed2-439f-8918-70f49dd8f822",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
