# Generated by Django 4.1.2 on 2022-10-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-322a4bf2-10b9-4142-84da-b3202ca4ebb4",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
