# Generated by Django 4.1.2 on 2022-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-73ba307b-5ee2-4da7-81b4-03c0f66d3811",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
