# Generated by Django 4.1.2 on 2022-10-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-8e736dcd-4885-453a-a965-082ead7edfae",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
