# Generated by Django 4.1.2 on 2022-10-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-098805f2-7c61-460b-a435-031047bb1c80",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
