# Generated by Django 4.1.2 on 2022-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-9a7dd1b2-acec-4487-bcd4-87abc9be3e8b",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
