# Generated by Django 4.1.2 on 2022-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-3245bfb7-3b48-4086-b075-590bd22aedd3",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
