# Generated by Django 4.1.2 on 2022-10-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0025_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-c5531db1-b539-44c6-a37f-088edad3de9f",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
