# Generated by Django 4.1.2 on 2022-10-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0026_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-4bd68cce-15d2-487a-aa1e-e9dd315d32a7",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
