# Generated by Django 4.1.2 on 2022-10-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0027_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-7d14d014-0765-489e-848f-326a10cefea1",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
