# Generated by Django 4.1.2 on 2022-10-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-6ab54528-25dc-4437-9749-0b012dc8b454",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
