# Generated by Django 4.1.2 on 2022-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-8d340f25-b380-47a2-852d-a3c83885699b",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
