# Generated by Django 4.1.2 on 2022-10-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0030_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-605a7b0f-4932-4d77-91b1-ca323765e8a2",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
