# Generated by Django 4.1.2 on 2022-10-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0031_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-d89fe043-39b1-4fea-81b1-910a268511cd",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
