# Generated by Django 4.1.2 on 2022-10-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0032_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-1c70ea6c-3c02-4073-a8c7-13a350a3592c",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
