# Generated by Django 4.1.2 on 2022-10-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0034_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-78098fbe-5cd5-44a0-83cf-44b3afcb1c50",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
