# Generated by Django 4.1.2 on 2022-10-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0035_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-961dd3bf-99c6-45e4-98b1-717c78cd1201",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
