# Generated by Django 4.1.2 on 2022-10-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0036_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-0e84da4c-631b-40a9-bfe1-50c47d2874d3",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
