# Generated by Django 4.1.2 on 2022-10-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0037_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-fb8fb71d-e7cb-454c-92a7-940dcc184512",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
