# Generated by Django 4.1.2 on 2022-10-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0038_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-164f0218-c805-4735-b19b-0db48df24d38",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
