# Generated by Django 4.1.2 on 2022-10-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0041_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-a6137838-8f1d-4614-8969-a652358f6945",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
