# Generated by Django 4.1.2 on 2022-10-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0042_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-0b942ed3-dac8-4e06-b98e-246ce7b3fe6f",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
