# Generated by Django 4.1.2 on 2022-10-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0043_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-3e3975fa-0ebc-4977-af0d-15c19b338e74",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
