# Generated by Django 4.1.2 on 2022-10-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0044_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-77068000-2eff-46c0-a745-0de2524071a8",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
