# Generated by Django 4.1.2 on 2022-10-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0048_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-7723e851-9d7a-49d1-bcea-ddd84be4fb1f",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
