# Generated by Django 4.1.2 on 2022-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0050_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-77c2c8fa-7b82-4ce9-a7a8-bdc93ac89345",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
