# Generated by Django 4.1.2 on 2022-10-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0051_alter_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_website",
            field=models.URLField(
                default="Sin Enlace", max_length=255, verbose_name="Link del Projecto"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                default="project-8f9d1865-ee5d-4c93-a671-df120dbe2e2c",
                unique=True,
                verbose_name="URL (sin espacios)",
            ),
        ),
    ]
