# Generated by Django 4.1.5 on 2023-01-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='project-709f807f-582a-486f-918d-ad8326433aae', unique=True, verbose_name='URL (sin espacios)'),
        ),
    ]
