# Generated by Django 4.1.5 on 2023-01-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0055_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='project-d95d1c15-ec1c-4b75-a4be-c498eac60097', unique=True, verbose_name='URL (sin espacios)'),
        ),
    ]
