# Generated by Django 4.1.7 on 2023-02-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0056_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='project-240a279b-d135-4aa5-b46f-73a4423c7882', unique=True, verbose_name='URL (sin espacios)'),
        ),
    ]
